Repository assimbly/gateway, pull requests merged in 2023-01, with the labels that each got.

#733 Camel email-component - oauth2 support
  build.gradle
Labels: feature

#744 Removed POM updater action
  .github/workflows/update-version.yml
Labels: bug

#742 Release patch 3.8.2
  .github/pr-labeler.yml
  .github/release-drafter.yml
  .github/workflows/maven-publish.yml
  .github/workflows/release-drafter.yml
  bin/README.md
  bin/win/updateversion.bat
  build.gradle
  gradle.properties
  null/cache/soap-component/37469e79-6634-4044-a075-46bfbf7778e8.wsdl
  null/cache/soap-component/43e768f7-1319-4349-a2ce-42149221a031.wsdl
  null/cache/soap-component/64cc6da6-31b4-4d33-a7cc-e8ae7a37fd18.wsdl
  null/cache/soap-component/67ae8b6a-57a9-4a11-9cb5-17cb402879a2.wsdl
  null/cache/soap-component/6abc207c-19db-4bd7-b953-17cb8b3bbffa.wsdl
  null/cache/soap-component/73e68184-fc29-4f04-b9b4-848ecebdf556.wsdl
  null/cache/soap-component/7ce224ba-693e-4fba-b117-e0abf558dd41.wsdl
  null/cache/soap-component/8b87b032-90c3-4620-bd8a-3b6608463d6d.wsdl
  null/cache/soap-component/8f6ad334-0544-4472-8933-a99a2ff564a8.wsdl
  package.json
  scripts/version/version.gradle
  scripts/version/versioned_files.json
  src/main/java/org/assimbly/gateway/config/importing/Import.java
  src/main/java/org/assimbly/gateway/config/importing/ImportXMLConnections.java
  src/main/java/org/assimbly/gateway/config/importing/ImportXMLEnvironmentVariables.java
  src/main/java/org/assimbly/gateway/config/importing/ImportXMLFlows.java
  src/main/java/org/assimbly/gateway/config/importing/ImportXMLGateways.java
  src/main/java/org/assimbly/gateway/config/importing/ImportXMLHeaders.java
  src/main/java/org/assimbly/gateway/config/importing/ImportXMLRoutes.java
  src/main/java/org/assimbly/gateway/web/rest/broker/BrokerResource.java
  src/main/java/org/assimbly/gateway/web/rest/gateway/AuthenticatorResource.java
  src/main/java/org/assimbly/gateway/web/rest/gateway/CertificateResource.java
  src/main/java/org/assimbly/gateway/web/rest/gateway/ManageCertificateResource.java
  src/main/java/org/assimbly/gateway/web/rest/integration/FlowResource.java
  src/main/resources/config/application.yml
  src/main/webapp/app/entities/broker/broker.service.ts
  src/main/webapp/app/entities/flow/editor/flow-editor-esb.component.ts
  src/main/webapp/app/entities/flow/flow-row.component.ts
  src/main/webapp/app/entities/flow/flow.service.ts
  src/test/java/org/assimbly/gateway/web/rest/FlowResourceIT.java
  src/test/java/org/assimbly/gateway/web/rest/FlowResourceIntTest.java
Labels: new version
